package TES::Plugin::Archive::BA2::Ent;

use FindBin;
use lib "$FindBin::Bin/../lib";

use File::Basename qw(basename dirname);
use Data::Dumper;
use Carp qw(confess);

use strict;
use warnings FATAL => qw(all);

local $SIG{__DIE__} = \&confess;
sub fatal { local $SIG{__DIE__}; die @_, "\n" }

local $Data::Dumper::Sortkeys = 1;
local $Data::Dumper::Useqq = 1;

our $VERSION = '$Id$';

# 256-element crc table, initialized at runtime
my $crc32_bs_pp_tab;
my $crc32_bs_pp_xtab;

sub crc32_bs_sanitize {
	my ($str) = @_;

	# Input to BSCRC32 is sanitized like so:
	# 1. All input is lowercase.
	# 2. All forward slashes are converted to backslashes.
	# 3. There is some kind of mapping of characters > 127
	#    that doesn't seem to follow any recognizable pattern.
	#    As a result, a translation table is used based on reverse
	#    engineering the checksums generated by Archive2 against
	#    the CRC32 table indexes for every single character
	#    that differs from it's normal index.
	# 4. For any string with an embedded NUL, calculation stops there.
	#
	# $ ba2dump -v archive2_sanchez.ba2
	#            6              12         -100.00%       3B8AD120        C90C2086    sanchez/1/Sá
	#           19              16           15.79%       A283809A        C90C2086    sanchez/2/S
	#            7              15         -114.29%       4BE025AF        C90C2086    sanchez/4/Sán
	#           17              21          -23.53%       3CE71539        AE18666A    sanchez/5/Sn
	#           11              19          -72.73%       D584B00C        00000000    sanchez/3/á
	#           14              22          -57.14%       A5EE4483        00000000    sanchez/6/ù
	#           18              26          -44.44%       D2E97415        61ABC75D    sanchez/7/María
	#            9              17          -88.89%       D2E97415        82E21285    sanchez/7/Marùa
	#           12              20          -66.67%       1D8C9AB5        82E21285    sanchez/10/Mar
	#           21              29          -38.10%       35515912        5D681B02    sanchez/9/í

	$str =~ tr%A-Z/%a-z\\%;

	return $str;
}

sub crc32_bs_pp_tab_init {
	use integer;

	my $poly = 0xedb88320;
	my $tab_sz = 256;
	my $crc;

	for (my $i = 0; $i < $tab_sz; $i++) {
		my $crc = $i;
		for (my $j = 8; $j--; ) {
			$crc = ($crc & 0x1) ? $poly ^ ($crc >> 1) : $crc >> 1;
		}

		$crc32_bs_pp_tab->[$i] = $crc;
		$crc32_bs_pp_xtab->{$crc} = $i;
	}
}

sub crc32_bs_pp_fast {
	# BSCRC32 differs from a "normal" CRC-32 in that
	# neither the initial or return value are XOR'ed.

	use integer;

	if (!defined $crc32_bs_pp_tab) {
		crc32_bs_pp_tab_init;
	}

	my $crc = 0;
	my @c = split('', crc32_bs_sanitize($_[0]));
	for (my $i = 0; $i < scalar @c; $i++) {
		$crc = $crc32_bs_pp_tab->[($crc ^ ord($c[$i])) & 0xff] ^ ($crc >> 8);
	}

	return $crc;
}

sub crc32_bs_pp {
	# BSCRC32 differs from a "normal" CRC-32 in that
	# neither the initial or return value are XOR'ed.

	use integer;

	my $crc = 0;
	my @c = split('', crc32_bs_sanitize($_[0]));
	for (my $i = 0; $i < scalar @c; $i++) {
		$crc ^= ord($c[$i]);
		for (my $j = 8; $j--; ) {
			$crc = ($crc >> 1) ^ (0xedb88320 & ~(($crc & 0x1) - 1));
		}
	}

	return $crc;
}

sub crc32_bs_xs {
	# BSCRC32 differs from a "normal" CRC-32 in that
	# neither the initial or return value are XOR'ed.
	# In this case an initial value of -1 and XOR -1
	# on the return value is done to be compatible
	# with the crc32() function but emulate a starting
	# crc of 0 and return with no XOR.
	return String::CRC32::crc32(crc32_bs_sanitize($_[0]), -1) ^ (-1 & 0xffffffff);
}

sub crc {
	my ($self, $data) = @_;
	return crc32_bs($data);
}

# Use XS module if available, otherwise fall back to PP version
eval { require String::CRC32 };
*crc32_bs = $@ ? \&crc32_bs_pp_fast : \&crc32_bs_xs;

sub name_split {
	my ($self, $name) = @_;

	# Normalize name to use forward-slash always (dirname also depends on this)
	$name //= $self->{'name'};
	$name =~ tr%\\%/%;

	my $dirname = dirname($name);
	my ($basename, $extension) = (basename($name), '');
	if ((my $idx = rindex($basename, '.')) > 0) {
		$extension = substr($basename, $idx + 1);
		$basename = substr($basename, 0, $idx);
	}

	# Normalize dirname to not be a single '.'
	return ($dirname ne '.' ? $dirname : '', $basename, $extension);
}

sub name {
	my ($self, $name) = @_;

	if (defined $name) {
		# Normalize name to use forward-slash always (name_split also depends on this)
		$name =~ tr%\\%/%;

		my ($dirname, $basename, $extension) = $self->name_split($name);
		$self->{'extension'} = lc substr($extension, 0, 4);
		$self->{'name_hash'} = $self->crc($basename);
		$self->{'dir_hash'} = $self->crc($dirname);
		$self->{'name'} = $name;
	}

	return $self->{'name'};
}

sub new {
	my ($class, %opts) = @_;
	map delete $opts{$_}, qw(data_skip verbose);

	my $self = bless { %opts }, ref $class || $class;
	if (defined $self->{'name'} && (!defined $self->{'name_hash'} || !defined $self->{'dir_hash'})) {
		$self->name($self->{'name'});
	}

	return $self;
}

use Class::XSAccessor (
	accessors => { map +($_, $_), qw(
		extension
		name_hash
		dir_hash
	) }
);

1;

__END__
