#PROGDIR="/cygdrive/c/Program Files (x86)/Steam/steamapps/common"
#PROGDIR_SHARED="/cygdrive/c/Program Files (x86)/Steam/steamapps/common/Fallout 4.shared"
#PROGDIR_TEMPLATE="/cygdrive/c/Program Files (x86)/Steam/steamapps/common/Fallout 4.template"

PROGDIR="/f/SteamLibrary/steamapps/common"
PROGDIR_SHARED="/f/SteamLibrary/steamapps/common/Fallout 4.shared"
PROGDIR_TEMPLATE="/f/SteamLibrary/steamapps/common/Fallout 4.template"

USERDIR="/cygdrive/c/Users/$USER/Documents/My Games"
USERDIR_SHARED="/cygdrive/c/Users/$USER/Documents/My Games/Fallout4.shared"
USERDIR_TEMPLATE="/cygdrive/c/Users/$USER/Documents/My Games/Fallout4.template"
USERDIR_LINK_SAVES=1

DATADIR="/cygdrive/c/Users/$USER/AppData/Local"
DATADIR_SHARED="/cygdrive/c/Users/$USER/AppData/Local/Fallout4.shared"
DATADIR_TEMPLATE="/cygdrive/c/Users/$USER/AppData/Local/Fallout4.template"

VERSION_CONTROL=1
