{
	Disable PreVis in selected exterior worldspaces/cells.
	Supports Fallout 4 only.
}
unit FO4_Precombined_Split;
const
	Debug = False;
	VersionInc = False;
	ConflictOnly = False;
	OutputFileSuffix = '_precombine_merge.esp';
var
	// Elements to keep from the most immediate plugin being overridden
	defer_tab: array [0..2] of TString;
	plugin_map: array [0..255] of IInterface;
	proc_total: integer;

function Initialize: integer;
begin
//	plugin_map := THashedStringList.Create;
	defer_tab[0] := 'XPRI';
	defer_tab[1] := 'RVIS';
	defer_tab[2] := 'VISI';

	proc_total := 0;
end;

function Process(e: IInterface): Integer;
var
	o, m, r, t, plugin: IInterface;
	s, mfile, ofile, pfile: TString;
	i, j, oc: integer;
	sl: TStringList;
begin
	// operate on the last override
	e := WinningOverride(e);

	// skip if this is the plugin file generated by this script
	if (Pos(OutputFileSuffix, GetFileName(e)) <> 0) then
		Exit;

	// skip non-cells
	if Signature(e) <> 'CELL' then
		Exit;

	// skip cells without precombination
	if not (ElementExists(e, 'XCRI') or ElementExists(e, 'PCMB')) then
		Exit;

	m := Master(e);
	oc := OverrideCount(m);

	if (oc = 0 or Equals(e, m)) then
		Exit
	else if oc = 1 then
		o := m
	else
		o := OverrideByIndex(m, oc - 2);

	mfile := GetFileName(m);
	ofile := GetFileName(o);

//	if (proc_total <> 0) and ((proc_total mod 256) = 0) then
//		AddMessage('Processed ' + IntToStr(proc_total) + ' CELL records...');

	i := GetLoadOrder(GetFile(o));
	plugin := plugin_map[i];
	if not Assigned(plugin) then begin
		pfile := ofile + OutputFileSuffix;
		for j := Pred(FileCount) downto 0 do begin
			r := FileByIndex(j);
			if GetFileName(r) = pfile then begin
				plugin := r;
				Break;
			end;
		end;

		if not Assigned(plugin) then begin
			// create new plugin
			AddMessage('Creating file: ' + pfile);

			plugin := AddNewFileName(pfile);
			if not Assigned(plugin) then begin
				AddMessage('Unable to create new file for ' + pfile);
				Result := 1;
				Exit;
			end;
		end;

		// add masters
		AddMasterIfMissing(plugin, mfile);
		if not Equals(o, m) then
			AddMasterIfMissing(plugin, ofile);

		plugin_map[i] := plugin;
	end;

	try
		try
			// XXX: xEdit will choke on delocalized plugins containing strings like '$FarmLocation'
			// XXX: due to it wrongly interpreting it as an integer value.
			r := wbCopyElementToFile(e, plugin, False, True);
		except
			// Deep copy failed, most likely due to bad XPRI data, attempt a per-element copy.
			// The vast majority of the time this branch will not be taken.
			on Ex: Exception do begin
				if Debug then begin
					AddMessage('Failed to deep copy: ' + FullPath(e));
					AddMessage('		reason: ' + Ex.Message);
					AddMessage('Attempting per element copy');
				end;

				r := wbCopyElementToFile(e, plugin, False, False);
				SetElementNativeValues(r, 'Record Header\Record Flags', GetElementNativeValues(e, 'Record Header\Record Flags'));

				for i := 0 to Pred(ElementCount(e)) do begin
					t := ElementByIndex(e, i);
					if not Assigned(t) then Continue;

					s := Signature(t);
					if not Assigned(s) then Continue;

					// If the previous deep copy failed it is extremely likely
					// it was due to these elements (see comment below).
					if (s = 'XPRI') or (s = 'RVIS') or (s = 'VISI') then
						Continue;

					if not ElementExists(r, s) then
						Add(r, s, True);

					ElementAssign(ElementBySignature(r, s), LowInteger, t, False);
				end;
			end;
		end;

		// Always defer to the previs data of the immediate override due to a CK bug
		// when >2 masters are used for precombine generation. 99% of the time the most
		// recent overridden refs are the actual refs used and these values will be
		// overwritten by previs generation anyway
		for i := 0 to Pred(length(defer_tab)) do begin
			s := defer_tab[i];
			if ElementExists(o, s) then begin
				if not ElementExists(r, s) then
					Add(r, s, True);
				ElementAssign(ElementBySignature(r, s), LowInteger, ElementBySignature(o, s), False);
			end else if ElementExists(r, s) then begin
				RemoveElement(r, s);
			end;
		end;

		SetFormVersion(r, GetFormVersion(e));
		SetFormVCS1(r, GetFormVCS1(e));
		SetFormVCS2(r, GetFormVCS2(e));

	except
		on Ex: Exception do begin
			AddMessage('Failed to copy: ' + FullPath(e));
			AddMessage('		reason: ' + Ex.Message);
		end;
	end;

	Inc(proc_total);
end;

// function Finalize: integer;
// var
//	plugin: IInterface;
//	i: integer;
// begin
//	for i := 0 to 255 do begin
//		plugin := plugin_map[i];
//		if Assigned(plugin) then
//			SortMasters(plugin);
//	end;
// end;

end.
